export const similarConcepts: { [ key: string ]: string } = {
    'react-js': 'reactjs',
    'reactnative': 'react native',
    'react-native': 'react native',
    'nodejs': 'node',
    'node js': 'node',
    'node-js': 'node',
    'asp.net': '.net',
    'dotnet': '.net',
    'dot net': '.net',
    'asp dot net': '.net',
    'dot-net': '.net',
    'asp': '.net',
    '.net': 'c#',
    'rest': 'rest api',
    'restful': 'rest api',
    'restapi': 'rest api',
    'rest-ful': 'rest api',
    'rest-api': 'rest api',
    'k8': 'kubernetes',
    'k8s': 'kubernetes',
    'unity2d': 'unity',
    'unity3d': 'unity',
    'unity 2d': 'unity',
    'unity-2d': 'unity',
    'unity 3d': 'unity',
    'unity-3d': 'unity',
    'cocos': 'cocos2d',
    'cocos-2d': 'cocos2d',
    'cocos 2d': 'cocos2d',
    'cocos2dx': 'cocos2d',
    'cocos 2dx': 'cocos2d',
    'cocos-2dx': 'cocos2d',
    'git': 'github',
    'git hub': 'github',
    'git-hub': 'gitbub',
    'github': 'github',
    'linked-in': 'linkedin',
    'linked in': 'linkedin'
}
